version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: RavenDB.Client
    versions:
    - 5.1.3
    - 5.1.4
    - 5.1.5
    - 5.1.6
  - dependency-name: Npgsql
    versions:
    - 5.0.3
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
